name: StellarQuickLogin
version: '${version}'
main: cn.stellarworld.quicklogin.StellarQuickLoginPlugin
api-version: '1.20'
softdepend:
  - AuthMe
commands:
  stellarquicklogin:
    description: Manage StellarQuickLogin
    usage: "/<command> <status|reload>"
    aliases: [sqlogin]
    permission: stellarquicklogin.admin
permissions:
  stellarquicklogin.admin:
    description: Manage StellarQuickLogin
    default: op
